// frontend/components/RadarChart.tsx
'use client';

export interface RadarSeries {
  name: string;
  /** Valores 0..max, en el mismo orden que `axes`. */
  values: number[];
  /** Color del trazo. */
  color: string;
  /** Relleno translúcido. */
  fill: string;
}

interface Props {
  axes: string[];
  series: RadarSeries[];
  max?: number;
}

/**
 * Radar / spider chart en SVG puro (sin libs). Réplica del estilo
 * "Resultados vs Autoevaluación": grilla concéntrica, ejes etiquetados,
 * polígonos translúcidos por serie y leyenda.
 */
export function RadarChart({ axes, series, max = 10 }: Props) {
  const size = 420;
  const cx = size / 2;
  const cy = size / 2;
  const radius = size / 2 - 70;
  const n = axes.length;
  const rings = 5;

  // Ángulo de cada eje (arranca arriba, sentido horario).
  const angleOf = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / n;
  const point = (i: number, value: number) => {
    const r = (Math.max(0, Math.min(max, value)) / max) * radius;
    const a = angleOf(i);
    return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as const;
  };
  const ringPath = (ring: number) => {
    const r = (ring / rings) * radius;
    return axes
      .map((_, i) => {
        const a = angleOf(i);
        return `${cx + r * Math.cos(a)},${cy + r * Math.sin(a)}`;
      })
      .join(' ');
  };
  const seriesPath = (values: number[]) =>
    values.map((v, i) => point(i, v).join(',')).join(' ');

  return (
    <div className="flex flex-col items-center">
      <svg width="100%" viewBox={`0 0 ${size} ${size}`} className="max-w-[460px]">
        {/* Anillos concéntricos */}
        {Array.from({ length: rings }, (_, k) => (
          <polygon
            key={k}
            points={ringPath(k + 1)}
            fill="none"
            stroke="#e2e8f0"
            strokeWidth={1}
          />
        ))}
        {/* Ejes + etiquetas */}
        {axes.map((label, i) => {
          const [x, y] = point(i, max);
          const [lx, ly] = (() => {
            const a = angleOf(i);
            const r = radius + 26;
            return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as const;
          })();
          const anchor = Math.abs(lx - cx) < 12 ? 'middle' : lx > cx ? 'start' : 'end';
          return (
            <g key={i}>
              <line x1={cx} y1={cy} x2={x} y2={y} stroke="#e2e8f0" strokeWidth={1} />
              <text
                x={lx}
                y={ly}
                textAnchor={anchor}
                dominantBaseline="middle"
                className="fill-slate-500"
                fontSize={12}
              >
                {label}
              </text>
            </g>
          );
        })}
        {/* Series */}
        {series.map((s, si) => (
          <g key={si}>
            <polygon points={seriesPath(s.values)} fill={s.fill} stroke={s.color} strokeWidth={2} />
            {s.values.map((v, i) => {
              const [x, y] = point(i, v);
              return <circle key={i} cx={x} cy={y} r={3} fill={s.color} />;
            })}
          </g>
        ))}
      </svg>

      <div className="flex flex-wrap items-center justify-center gap-4 mt-2">
        {series.map((s, i) => (
          <div key={i} className="flex items-center gap-2 text-sm text-slate-600">
            <span className="inline-block w-4 h-2 rounded" style={{ backgroundColor: s.color }} />
            {s.name}
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend-angular/src/app/components/radar-chart/radar-chart.component.ts
import { Component, Input, OnChanges } from '@angular/core';

export interface RadarSeries {
  name: string;
  values: number[];
  color: string;
  fill: string;
}

interface AxisData { label: string; x: number; y: number; lx: number; ly: number; anchor: string; }
interface SeriesData { name: string; color: string; fill: string; points: string; dots: { x: number; y: number }[]; }

@Component({
  selector: 'app-radar-chart',
  template: `
    <div class="flex flex-col items-center">
      <svg width="100%" [attr.viewBox]="'0 0 ' + size + ' ' + size" class="max-w-[460px]">
        <polygon *ngFor="let ring of rings" [attr.points]="ring" fill="none" stroke="#e2e8f0" stroke-width="1" />
        <g *ngFor="let axis of axisData">
          <line [attr.x1]="cx" [attr.y1]="cy" [attr.x2]="axis.x" [attr.y2]="axis.y" stroke="#e2e8f0" stroke-width="1" />
          <text [attr.x]="axis.lx" [attr.y]="axis.ly" [attr.text-anchor]="axis.anchor"
            dominant-baseline="middle" class="fill-slate-500" font-size="12">{{ axis.label }}</text>
        </g>
        <g *ngFor="let s of seriesData">
          <polygon [attr.points]="s.points" [attr.fill]="s.fill" [attr.stroke]="s.color" stroke-width="2" />
          <circle *ngFor="let d of s.dots" [attr.cx]="d.x" [attr.cy]="d.y" r="3" [attr.fill]="s.color" />
        </g>
      </svg>
      <div class="flex flex-wrap items-center justify-center gap-4 mt-2">
        <div *ngFor="let s of series" class="flex items-center gap-2 text-sm text-slate-600">
          <span class="inline-block w-4 h-2 rounded" [style.backgroundColor]="s.color"></span>
          {{ s.name }}
        </div>
      </div>
    </div>
  `,
})
export class RadarChartComponent implements OnChanges {
  @Input() axes: string[] = [];
  @Input() series: RadarSeries[] = [];
  @Input() max = 10;

  size = 420;
  cx = 210;
  cy = 210;
  radius = 140;
  rings: string[] = [];
  axisData: AxisData[] = [];
  seriesData: SeriesData[] = [];

  ngOnChanges(): void {
    this.cx = this.size / 2;
    this.cy = this.size / 2;
    this.radius = this.size / 2 - 70;
    const n = this.axes.length;
    const rings = 5;

    const angleOf = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / n;
    const point = (i: number, value: number): [number, number] => {
      const r = (Math.max(0, Math.min(this.max, value)) / this.max) * this.radius;
      const a = angleOf(i);
      return [this.cx + r * Math.cos(a), this.cy + r * Math.sin(a)];
    };

    this.rings = Array.from({ length: rings }, (_, k) =>
      this.axes.map((_, i) => {
        const r = ((k + 1) / rings) * this.radius;
        const a = angleOf(i);
        return `${this.cx + r * Math.cos(a)},${this.cy + r * Math.sin(a)}`;
      }).join(' ')
    );

    this.axisData = this.axes.map((label, i) => {
      const [x, y] = point(i, this.max);
      const a = angleOf(i);
      const lr = this.radius + 26;
      const lx = this.cx + lr * Math.cos(a);
      const ly = this.cy + lr * Math.sin(a);
      const anchor = Math.abs(lx - this.cx) < 12 ? 'middle' : lx > this.cx ? 'start' : 'end';
      return { label, x, y, lx, ly, anchor };
    });

    this.seriesData = this.series.map(s => ({
      name: s.name,
      color: s.color,
      fill: s.fill,
      points: s.values.map((v, i) => point(i, v).join(',')).join(' '),
      dots: s.values.map((v, i) => { const [x, y] = point(i, v); return { x, y }; }),
    }));
  }
}
